plugins {
    id 'java-library'
    id 'eclipse'
    id 'idea'
    id 'maven-publish'
    id 'net.neoforged.moddev.legacyforge' version '2.0.141'
}

version = mod_version + "-forge"
group = mod_group_id

repositories {
    mavenLocal()
}

base {
    archivesName = mod_id
}

java.toolchain.languageVersion = JavaLanguageVersion.of(17)

boolean isRunningInIdea = System.getProperty("idea.active") == "true"

legacyForge {
    version = project.minecraft_version + '-' + project.forge_version

    parchment {
        mappingsVersion = project.parchment_mappings_version
        minecraftVersion = project.parchment_minecraft_version
    }

    accessTransformers = project.files('src/main/resources/META-INF/accesstransformer.cfg')

    runs {
        client {
            client()
            systemProperty 'forge.enabledGameTestNamespaces', project.mod_id
        }
        server {
            server()
            programArgument '--nogui'
            systemProperty 'forge.enabledGameTestNamespaces', project.mod_id
        }
        data {
            data()
            programArguments.addAll '--mod', project.mod_id, '--all', '--output', file('src/generated/resources/').getAbsolutePath(), '--existing', file('src/main/resources/').getAbsolutePath()
        }
        configureEach {
            systemProperty 'forge.logging.markers', 'REGISTRIES'
            logLevel = org.slf4j.event.Level.DEBUG
            jvmArguments.addAll([
                    // 忽略无效指令，避免有的人没安装 JetBrain Runtime 无法启动游戏
                    "-XX:+IgnoreUnrecognizedVMOptions",
                    // 启用 JetBrain Runtime 热重载功能
                    "-XX:+AllowEnhancedClassRedefinition"
            ])
            if (isRunningInIdea) {
                systemProperty "terminal.jline", "true"
            }
        }
    }

    mods {
        "${mod_id}" {
            sourceSet(sourceSets.main)
        }
    }
}

sourceSets.main.resources { srcDir 'src/generated/resources' }

configurations {
    runtimeClasspath.extendsFrom localRuntime
}
obfuscation {
    createRemappingConfiguration(configurations.localRuntime)
}

repositories {
    flatDir {
        dir 'libs'
    }
    maven {
        // location of the maven that hosts JEI files before January 2023
        name = "Progwml6's maven"
        url = "https://dvs1.progwml6.com/files/maven/"
    }
    maven {
        // location of the maven that hosts JEI files since January 2023
        name = "Jared's maven"
        url = "https://maven.blamejared.com/"
    }
    maven {
        // location of a maven mirror for JEI files, as a fallback
        name = "ModMaven"
        url = "https://modmaven.dev"
    }
    maven {
        url = "https://www.cursemaven.com"
    }
    maven {
        url = "https://maven.bawnorton.com/releases"
    }
    maven {
        name = "Curios"
        url = uri("https://maven.theillusivec4.top/")
    }
    maven {
        name "org.confluenceReleases"
        url "https://maven.confluence.ink/releases"
    }
    maven {
        name "org.confluenceSnapshots"
        url "https://maven.confluence.ink/snapshots"
    }
}

boolean slim = true

dependencies {
    modImplementation "top.theillusivec4.curios:curios-forge:${curios_version}"
    modCompileOnly "mezz.jei:jei-${minecraft_version}-common-api:${jei_version}"
    modCompileOnly("mezz.jei:jei-${minecraft_version}-forge-api:${jei_version}")
    modRuntimeOnly("mezz.jei:jei-${minecraft_version}-forge:${jei_version}")

    compileOnly(annotationProcessor("io.github.llamalad7:mixinextras-common:0.5.3"))
    if (slim) {
        modImplementation("org.mesdag:ParticleStorm:${particle_storm_version}-forge")
        modImplementation project(":Confluence-Magic-Lib")
        modImplementation project(":PortLib")
        implementation("io.github.llamalad7:mixinextras-forge:0.5.3")
    } else {
        jarJar(modImplementation("org.mesdag:ParticleStorm:${particle_storm_version}-forge"))
//        modImplementation(jarJar("org.confluence.lib:Confluence-Magic-Lib:${confluence_lib_version}-forge"))
        modImplementation(project(":Confluence-Magic-Lib"))
        jarJar(project(":Confluence-Magic-Lib"))
//        modImplementation jarJar("org.mesdag.portlib:MesdagPortLib:${portlib_version}")
        modImplementation(project(":PortLib"))
        jarJar(project(":PortLib"))
        jarJar(implementation("io.github.llamalad7:mixinextras-forge:0.5.3"))
    }
    annotationProcessor 'org.spongepowered:mixin:0.8.5:processor'
}

mixin {
    add sourceSets.main, "${mod_id}.refmap.json"
    config "${mod_id}.mixins.json"
}

jar {
    manifest.attributes([
            "MixinConfigs": "${mod_id}.mixins.json"
    ])
}


import groovy.json.JsonBuilder
import groovy.json.JsonSlurper

tasks.named('jarJar') { jarJarTask ->
    String metadataPath = jarJarTask.project.buildDir.toPath()
            .resolve('generated/jarJar/META-INF/jarjar/metadata.json')
            .toFile()
            .absolutePath
    jarJarTask.doLast {
        def metadataFile = new File(metadataPath)
        if (metadataFile.exists()) {
            def json = new JsonSlurper().parse(metadataFile)
            json.jars.each { jar ->
                if (jar.identifier.artifact == 'ParticleStorm') {
                    jar.version.range = jar.version.range.replace('-forge', '')
                    jar.version.artifactVersion = jar.version.artifactVersion.replace('-forge', '')
                }
            }
            metadataFile.text = new JsonBuilder(json).toPrettyString()
        }
    }
}

tasks.withType(ProcessResources).configureEach {
    var replaceProperties = [
            minecraft_version      : minecraft_version,
            minecraft_version_range: minecraft_version_range,
            forge_version          : forge_version,
            forge_version_range    : forge_version_range,
            loader_version_range   : loader_version_range,
            mod_id                 : mod_id,
            mod_name               : mod_name,
            mod_license            : mod_license,
            mod_version            : mod_version,
            mod_authors            : mod_authors,
            mod_description        : mod_description,
            curios_version         : curios_version
    ]
    inputs.properties replaceProperties

    filesMatching(['META-INF/mods.toml']) {
        expand replaceProperties
    }
}

java.withSourcesJar()
ext {
    releasesUrl = "https://maven.confluence.ink/releases"
    snapshotsUrl = "https://maven.confluence.ink/snapshots"
}
publishing {
    publications {
        register('mavenJava', MavenPublication) {
            from components.java
        }
    }
    repositories {
        maven {
            name = "Confluence"
            url = version.toString().endsWith("SNAPSHOT") ? snapshotsUrl : releasesUrl
            credentials {
                username = System.getenv("MAGIC_TEAM_USERNAME")
                password = System.getenv("MAGIC_TEAM_TOKEN")
            }
        }
    }
}

idea {
    module {
        downloadSources = true
        downloadJavadoc = true
    }
}

tasks.withType(JavaCompile) {
    options.encoding = 'UTF-8'
}
