org.gradle.jvmargs=-Xmx4G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

minecraft_version=1.20.1
minecraft_version_range=[1.20.1,1.21)
forge_version=47.4.20
forge_version_range=[47.4.20,)
loader_version_range=[47,)
parchment_minecraft_version=1.20.1
parchment_mappings_version=2023.09.03

mod_id=terra_curio
mod_name=TerraCurio
mod_license=LGPL-3.0
mod_version=1.3.1.2
mod_group_id=org.confluence
mod_authors=Westernat, XiaoHuNao
mod_description=Accessories part

curios_version=5.14.1+1.20.1
particle_storm_version=1.3.1.1
confluence_lib_version=0.1.0
portlib_version=0.1.2
jei_version=15.20.0.129

#systemProp.http.proxyHost=localhost
#systemProp.http.proxyPort=7897
#systemProp.https.proxyHost=localhost
#systemProp.https.proxyPort=7897
