package org.confluence.terra_curio.datagen;

import net.minecraft.data.PackOutput;
import net.minecraft.world.item.Item;
import net.minecraftforge.common.data.LanguageProvider;
import org.confluence.terra_curio.TerraCurio;
import org.confluence.terra_curio.datagen.limit.CustomName;
import org.confluence.terra_curio.effect.ModEffects;
import org.confluence.terra_curio.entity.ModEntities;
import org.confluence.terra_curio.item.ModItems;

import java.util.Arrays;
import java.util.stream.Collectors;

public class ModEnglishProvider extends LanguageProvider {
    public ModEnglishProvider(PackOutput output) {
        super(output, TerraCurio.MODID, "en_us");
    }

    @Override
    protected void addTranslations() {
        add("creativetab.terra_curio.accessories", "Terra Curio");

        add("curios.tooltip.speed_boots", "The wearer can run super fast");
        add("curios.tooltip.may_fly", "Allows flight");
        add("curios.tooltip.jump_boost", "Increases jump height");
        add("curios.tooltip.multi_jump", "Allows the holder to double jump");
        add("curios.tooltip.fall_resistance", "Increases fall resistance");
        add("curios.tooltip.negates_fall_damage", "Negates fall damage");
        add("curios.tooltip.watch", "Tell the time");
        add("curios.tooltip.fire_immune", "Grants immunity to fire blocks");
        add("curios.tooltip.fluid_walk.part", "Provides the ability to walk on water & honey");
        add("curios.tooltip.fluid_walk.all", "Provides the ability t walk on water, honey & lava");
        add("curios.tooltip.lava_immune", "Provides 7 seconds of immunity to lava");
        add("curios.tooltip.lava_hurt_reduce", "Reduces damage from touching lava");
        add("curios.tooltip.fire_attack", "Melee attacks inflict fire damage");
        add("curios.tooltip.auto_attack", "Enables auto swing for melee weapons");
        add("curios.tooltip.aggro_attach", "Enemies are more likely to target you");
        add("curios.tooltip.armor_pass", "Increases armor penetration by %s");
        add("curios.tooltip.compass", "Displays horizontal position");
        add("curios.tooltip.depth_meter", "Displays depth");
        add("curios.tooltip.dps_meter", "Displays your damage per second");
        add("curios.tooltip.fishermans_pocket_guide", "Displays fishing information");
        add("curios.tooltip.life_form_analyzer", "Displays the name of rare creatures around you");
        add("curios.tooltip.metal_detector", "Displays the most valuable ore around you");
        add("curios.tooltip.radar", "Detects enemies around you");
        add("curios.tooltip.sextant", "Displays the phase of the moon");
        add("curios.tooltip.stopwatch", "Displays how fast the player is moving");
        add("curios.tooltip.tally_counter", "Displays how many monsters have been killed");
        add("curios.tooltip.weather_radio", "Displays the weather");
        add("curios.tooltip.scope", "Increases view range for ranged weapons");
        add("curios.tooltip.scope2", "Hold ranged weapon and crouch to zoom out");
        add("curios.tooltip.wall_climb", "Allows the ability to climb walls, hold shift key to slide down");
        add("curios.tooltip.wall_slide", "Allows the ability to slide down walls, hold shift key to slide down quickly");
        add("curios.tooltip.tabi", "Allows the ability to dash while double tap a direction");
        add("curios.tooltip.dodge", "Gives a chance to dodge attacks");

        add("info.terra_curio.time", "Time: [%s:%s]");
        add("info.terra_curio.radar", "Enemies: %s");
        add("info.terra_curio.compass.east", "East: %s, ");
        add("info.terra_curio.compass.west", "West: %s, ");
        add("info.terra_curio.compass.south", "South: %s");
        add("info.terra_curio.compass.north", "North: %s");
        add("info.terra_curio.depth_meter.surface", "Surface: %s");
        add("info.terra_curio.depth_meter.underground", "Underground: %s");
        add("info.terra_curio.tally_counter.unknown", "Kill count unavailable");
        add("info.terra_curio.tally_counter", "Killed '");
        add("info.terra_curio.life_form_analyzer.none", "No rare creatures nearby!");
        add("info.terra_curio.life_form_analyzer", "%s detected nearby!");
        add("info.terra_curio.metal_detector.none", "No treasure nearby!");
        add("info.terra_curio.metal_detector", "%s detected nearby!");
        add("info.terra_curio.stopwatch", "Speed: %s m/s");
        add("info.terra_curio.dps_meter", "DPS: %s");
        add("info.terra_curio.sextant.0", "Moon phase: Full Moon");
        add("info.terra_curio.sextant.1", "Moon phase: Waning Gibbous");
        add("info.terra_curio.sextant.2", "Moon phase: Third Quarter");
        add("info.terra_curio.sextant.3", "Moon phase: Waning Crescent");
        add("info.terra_curio.sextant.4", "Moon phase: New Moon");
        add("info.terra_curio.sextant.5", "Moon phase: Waxing Crescent");
        add("info.terra_curio.sextant.6", "Moon phase: First Quarter");
        add("info.terra_curio.sextant.7", "Moon phase: Waxing Gibbous");
        add("info.terra_curio.weather_radio.clear", "Weather: Clear");
        add("info.terra_curio.weather_radio.cloudy", "Weather: Cloudy");
        add("info.terra_curio.weather_radio.rain", "Weather: Rain");
        add("info.terra_curio.weather_radio.snow", "Weather: Snow");
        add("info.terra_curio.weather_radio.thunder", "Weather: Thunder");
        add("info.terra_curio.fishermans_pocket_guide", "Fishing Power: %s");

        add("key.terra_curio.metal_detector", "Detect Metal");
        add("key.terra_curio.step_stool", "Step Stool");

        add("curios.identifier.accessory", "Accessory");
        add("curios.modifiers.accessory", "When worn as accessory:");

        add("item.terra_curio.demon_heart.tooltip", "Permanently increases the number of accessory slots");
        add("item.terra_curio.vitamins.tooltip", "Immunity to Weakness");
        add("item.terra_curio.fast_clock.tooltip", "Immunity to Slow");
        add("item.terra_curio.blindfold.tooltip", "Immunity to Blindness");
        add("item.terra_curio.bezoar.tooltip", "Immunity to Poison");
        add("item.terra_curio.trifold_map.tooltip", "Immunity to Nausea");
        add("item.terra_curio.the_plan.tooltip", "Immunity to Slow and Nausea");
        add("item.terra_curio.holy_water.tooltip", "Immunity to Wither");
        add("item.terra_curio.energy_bar.tooltip", "Immunity to Hunger");
        add("item.terra_curio.flashlight.tooltip", "Immunity to Darkness");
        add("item.terra_curio.hand_drill.tooltip", "Immunity to Mining Fatigue");
        add("item.terra_curio.shot_put.tooltip", "Immunity to Levitation");
        add("item.terra_curio.searchlight.tooltip", "Immunity to Blindness and Darkness");
        add("item.terra_curio.detoxification_capsule.tooltip", "Immunity to Poison and Wither");
        add("item.terra_curio.explorers_equipment.tooltip", "Immunity to Mining Fatigue and Levitation");
        add("item.terra_curio.nutrient_solution.tooltip", "Immunity to Weakness and Hunger");
        add("item.terra_curio.ankh_charm.tooltip", "Grants immunity to most debuffs");
        add("item.terra_curio.cobalt_shield.tooltip", "Grants immunity to knockback");
        add("item.terra_curio.band_of_regeneration.tooltip", "Slowly regenerates life");
        add("item.terra_curio.mechanical_lens.tooltip", "Grants improved wire vision");
        add("item.terra_curio.spectre_goggles.tooltip", "Enables Echo Sight, showing hidden blocks");
        add("item.terra_curio.magiluminescence.tooltip", "Increases movement speed and acceleration");
        add("item.terra_curio.magiluminescence.tooltip3", "'A brief light in my dark life.'");
        add("item.terra_curio.sandstorm_on_a_bottle.tooltip", "Allows the holder to do an improved double jump");
        add("item.terra_curio.ice_skates.tooltip", "Provides extra mobility on ice");
        add("item.terra_curio.dunerider_boots.tooltip", "The wearer can run super fast, and even faster on sand");
        add("item.terra_curio.dunerider_boots.tooltip2", "'Walk without rhythm and you won't attract the worm'");
        add("item.terra_curio.lucky_horseshoe.tooltip", "'Said to bring good fortune and keep evil spirits at bay'");
        add("item.terra_curio.lightning_boots.tooltip", "Allows flight, super fast running");
        add("item.terra_curio.horseshoe_balloon.tooltip", "Increases jump height and negates fall damage");
        add("item.terra_curio.lava_waders.tooltip2", "Grants immunity to fire blocks and 7 seconds of immunity to lava");
        add("item.terra_curio.bundle_of_balloons.tooltip", "Allows the holder to quadruple jump");
        add("item.terra_curio.bundle_of_horseshoe_balloon.tooltip", "Allows the holder to quadruple jump");
        add("item.terra_curio.bundle_of_horseshoe_balloon.tooltip2", "Increases jump height and negates fall damage");
        add("item.terra_curio.water_walking_boots.tooltip", "Provides the ability to walk on water & honey");
        add("item.terra_curio.magma_skull.tooltip", "Immunity to fire blocks, melee attacks deal fire damage");
        add("item.terra_curio.frostspark_boots.tooltip", "Allows flight, super fast running, and extra mobility on ice");
        add("item.terra_curio.sun_stone.tooltip", "During daytime, grants minor increase");
        add("item.terra_curio.moon_stone.tooltip", "During nighttime, grants minor increase");
        add("item.terra_curio.putrid_scent.tooltip", "Enemies are less likely to target you");
        add("item.terra_curio.panic_necklace.tooltip", "Increases movement speed after taking damage");
        add("item.terra_curio.paladins_shield.tooltip", "Absorbs 25% of damage done to players on your team when above 25% life");
        add("item.terra_curio.frozen_shield.tooltip", "Absorbs 25% of damage done to players on your team when above 25% life");
        add("item.terra_curio.frozen_shield.tooltip2", "Puts a shell around the owner when below 50% life that reduces damage by 25%");
        add("item.terra_curio.frozen_turtle_shell.tooltip", "Puts a shell around the owner when below 50% life that reduces damage by 25%");
        add("item.terra_curio.fire_gauntlet.tooltip", "Increases melee knockback and melee attacks inflict fire damage");
        add("item.terra_curio.cross_necklace.tooltip", "Increases length of invincibility after taking damage");
        add("item.terra_curio.terraspark_boots.tooltip2", "Grants immunity to fire blocks and 7 seconds of immunity to lava");
        add("item.terra_curio.fledgling_wings.tooltip", "Allows flight and slow fall");
        add("item.terra_curio.worm_scarf.tooltip", "Reduces damage taken by 17%");
        add("item.terra_curio.shield_of_cthulhu.tooltip", "Allows the player to dash into the enemy, sprinting to dsh");
        add("item.terra_curio.brain_of_confusion.tooltip", "Has a chance to create illusions and dodge an attack");
        add("item.terra_curio.brain_of_confusion.tooltip2", "Temporarily increase critical chance after dodge");
        add("item.terra_curio.brain_of_confusion.tooltip3", "May confuse nearby enemies after being struck");
        add("item.terra_curio.royal_gel.tooltip", "Slimes become friendly");
        add("item.terra_curio.arcane_flower.tooltip3", "The enemy is unlikely to target you");
        add("item.terra_curio.celestial_stone.tooltip", "Slightly increases the attribute value");
        add("item.terra_curio.charm_of_myths.tooltip", "Provides health regeneration and reduces the cooldown of healing potions");
        add("item.terra_curio.philosophers_stone.tooltip", "Reduced the cooldown of Healing Potions");
        add("item.terra_curio.gold_ring.tooltip", "Expanded coin pickup");
        add("item.terra_curio.gravity_globe.tooltip", "Allows the holder to reverse gravity");
        add("item.terra_curio.gravity_globe.tooltip2", "Press Jump to change gravity");
        add("item.terra_curio.ancient_chisel.tooltip2", "“Age-old problems require age-old solutions”");
        add("item.terra_curio.treasure_magnet.tooltip", "Expanded item pickup");
        add("item.terra_curio.flower_boots.tooltip", "Flowers grow on the grass you walk on");
        add("item.terra_curio.hand_warmer.tooltip", "Provides immunity to chill and freezing effects");
        add("item.terra_curio.star_cloak.tooltip", "Causes stars to fall after taking damage");
        add("item.terra_curio.honey_comb.tooltip", "Releases bees and douses the user in honey when damaged");
        add("item.terra_curio.sweetheart_necklace.tooltip", "When damaged, the bee is released and the user is immersed in honey and increases movement speed");
        add("item.terra_curio.hive_pack.tooltip", "Increases the strength of friendly bees");
        add("item.terra_curio.magic_quiver.tooltip2", "20% chance to not consume arrows");
        add("item.terra_curio.molten_quiver.tooltip", "Lights wooden arrows ablaze");
        add("item.terra_curio.molten_quiver.tooltip2", "'Quiver in fear!'");
        add("item.terra_curio.recon_scope.tooltip", "'Enemy spotted'");
        add("item.terra_curio.portable_cement_mixer.tooltip", "Decreased 'Right Click Delay' by 1");
        add("item.terra_curio.brick_layer.tooltip", "Decreased 'Right Click Delay' by 1");
        add("item.terra_curio.architect_gizmo_pack.tooltip", "Decreased 'Right Click Delay' by 2, cannot stack the decrease of its materials");
        add("item.terra_curio.climbing_claws.tooltip", "Improved ability if combined with Shoe Spikes");
        add("item.terra_curio.shoe_spikes.tooltip", "Improved ability if combined with Climbing Claws");
        add("item.terra_curio.frog_gear.tooltip", "'It ain't easy being green'");
        add("item.terra_curio.hand_of_creation.tooltip2", "Decreased 'Right Click Delay' by 3, cannot stack the decrease of its material");
        add("item.terra_curio.step_stool.tooltip", "Press ↑ key to stand higher, and press Shift key to down");
        add("item.terra_curio.step_stool.tooltip2", "Extra Step: %s");
        add("item.terra_curio.magic_mirror.tooltip", "Gaze in the mirror to return home");
        add("item.terra_curio.cell_phone.tooltip", "Displays everything");
        add("item.terra_curio.cell_phone.tooltip2", "Allows you to return home at will");

        add("item.terra_curio.aglet.info", "It can be found in Shipwreck Chests.");
        add("item.terra_curio.climbing_claws.info", "It have a Chance to be dropped from Spider.");
        add("item.terra_curio.cloud_in_a_bottle.info", "It can be found in Chests in the Mineshaft and Dungeon.");
        add("item.terra_curio.dunerider_boots.info", "It have a Chance to be dropped from Husk.");
        add("item.terra_curio.fart_in_a_jar.info", "It have a Chance to be dropped from Ghost.");
        add("item.terra_curio.flipper.info", "It can be found in Chests in the Shipwreck.");
        add("item.terra_curio.flurry_boots.info", "It can be found in Igloo's chest.");
        add("item.terra_curio.frog_leg.info", "The Frog Leg have a Chance to be dropped from Frog.");
        add("item.terra_curio.hermes_boots.info", "It can be found in Chests in the Village Armorer.");
        add("item.terra_curio.lava_charm.info", "It have a Chance to be dropped from Blaze.");
        add("item.terra_curio.lucky_horseshoe.info", "It can be discovered in chests found within Desert Pyramids, End City, Jungle Pyramids, or Ancient Cities.");
        add("item.terra_curio.magiluminescence.info", "It can be found in End City Chests.");
        add("item.terra_curio.sailfish_boots.info", "It can be found in Shipwreck Chests.");
        add("item.terra_curio.sandstorm_in_a_bottle.info", "It can be found in Chests in the Desert Pyramid.");
        add("item.terra_curio.shiny_red_balloon.info", "When the player has the Hero of the Village effect, the librarian has a chance to give the player this item.It can be found in chests in plains villages.");
        add("item.terra_curio.shoe_spikes.info", "It have a Chance to be dropped from Cave Spider.");
        add("item.terra_curio.step_stool.info", "You can use Step Stool to upgrade its Extra Step from Smithing Table");
        add("item.terra_curio.tabi.info", "It can be found in Chests in the Fortress.");
        add("item.terra_curio.tsunami_in_a_bottle.info", "It can be found in Shipwreck Chests");
        add("item.terra_curio.water_walking_boots.info", "It can be found in Ocean Ruins Chests.");
        add("item.terra_curio.depth_meter.info", "The Depth Meter have a Chance to be dropped from Bats.");
        add("item.terra_curio.compass.info", "The Compass have a Chance to be dropped from Bats.");
        add("item.terra_curio.dps_meter.info", "The DPS Meter have a Chance to be dropped from Creeper.");
        add("item.terra_curio.fishermans_pocket_guide.info", "This item can be located in the chests found within Fisherman Villagers' houses.");
        add("item.terra_curio.life_form_analyzer.info", "The Lifeform Analyzer have a Chance to be dropped from Glow Squid.");
        add("item.terra_curio.metal_detector.info", "The Metal Detector have a Chance to be dropped from Warden.");
        add("item.terra_curio.radar.info", "The Radar have a Chance to be dropped from Bats.");
        add("item.terra_curio.sextant.info", "This item can be located in the chests found within Fisherman Villagers' houses.");
        add("item.terra_curio.tally_counter.info", "The Tally Counter a Chance to be dropped from Creeper.");
        add("item.terra_curio.weather_radio.info", "This item can be located in the chests found within Fisherman Villagers' houses.");
        add("item.terra_curio.band_of_regeneration.info", "The Band of Regeneration is an accessory that have a Chance to be dropped from Witch");
        add("item.terra_curio.angler_earring.info", "This item can be located in the chests found within Fisherman Villagers' houses.");
        add("item.terra_curio.brain_of_confusion.info", "It have a Chance to be dropped from Zombie Villager.");
        add("item.terra_curio.gravity_globe.info", "It have a Chance to be dropped from Shulker.");
        add("item.terra_curio.hive_pack.info", "It have a Chance to be dropped from Bee.");
        add("item.terra_curio.royal_gel.info", "It have a Chance to be dropped from Slime.");
        add("item.terra_curio.shield_of_cthulhu.info", "It have a Chance to be dropped from Ravager.");
        add("item.terra_curio.worm_scarf.info", "When a player has a tamed cat, the cat may give the player this item when they wake up.");
        add("item.terra_curio.ancient_chisel.info", "The item can be pass the Archaeology to obtained.");
        add("item.terra_curio.brick_layer.info", "This item can be located in the chests found within Toolsmith Villagers' houses.");
        add("item.terra_curio.extendo_grip.info", "It can be discovered in chests found within Desert Pyramids.");
        add("item.terra_curio.portable_cement_mixer.info", "This item can be located in the chests found within Toolsmith Villagers' houses.");
        add("item.terra_curio.toolbelt.info", "This item can be located in the chests found within Toolsmith Villagers' houses.");
        add("item.terra_curio.toolbox.info", "The item can be located in the chests found within Toolsmith Villagers' houses.");
        add("item.terra_curio.flower_boots.info", "It has a chance of falling from digging through Moss Block.");
        add("item.terra_curio.treasure_magnet.info", "It can be discovered in chests found within Desert Pyramids, End City, Jungle Pyramids, or Ancient Cities.");
        add("item.terra_curio.bezoar.info", "It have a Chance to be dropped from Cave Spider.");
        add("item.terra_curio.black_belt.info", "It have a Chance to be dropped from Wither Skeleton.");
        add("item.terra_curio.blindfold.info", "It can be discovered in chests found within Ancient City.");
        add("item.terra_curio.cobalt_shield.info", "It have a Chance to be dropped from Ravager.");
        add("item.terra_curio.cross_necklace.info", "It have a Chance to be dropped from Evoker.");
        add("item.terra_curio.energy_bar.info", "It have a Chance to be dropped from Zombified Piglin.");
        add("item.terra_curio.eye_of_the_golem.info", "It can be discovered in chests found within Jungle Pyramids.");
        add("item.terra_curio.fast_clock.info", "It have a Chance to be dropped from Stray.");
        add("item.terra_curio.feral_claws.info", "It can be discovered in chests found within Jungle Pyramids.");
        add("item.terra_curio.flashlight.info", "It can be discovered in chests found within Stronghold.");
        add("item.terra_curio.flesh_knuckles.info", "It have a Chance to be dropped from Piglin Brute.");
        add("item.terra_curio.frozen_turtle_shell.info", "When the Turtle died for Freezing chance to dropped this item.");
        add("item.terra_curio.hand_drill.info", "It have a Chance to be dropped from Elder Guardian.");
        add("item.terra_curio.holy_water.info", "It have a Chance to be dropped from Wither Skeleton.");
        add("item.terra_curio.honey_comb.info", "It have a Chance to be dropped from Bee.");
        add("item.terra_curio.magic_quiver.info", "This item have a Chance to be dropped from Skeleton.");
        add("item.terra_curio.magma_stone.info", "It have a Chance to be dropped from Blaze.");
        add("item.terra_curio.moon_stone.info", "It have a Chance to be dropped from Phantom.");
        add("item.terra_curio.obsidian_rose.info", "It can be discovered in chests found within Bastion Remnant.");
        add("item.terra_curio.paladins_shield.info", "It to be dropped from Ender Dragon.");
        add("item.terra_curio.panic_necklace.info", "It can be found in Chests in the Dungeon.");
        add("item.terra_curio.putrid_scent.info", "It can be found in Chests in the Dungeon.");
        add("item.terra_curio.ranger_emblem.info", "It have a Chance to be dropped from Skeleton.");
        add("item.terra_curio.rifle_scope.info", "It have a Chance to be dropped from Enderman.");
        add("item.terra_curio.shackle.info", "It can be found in Chests in the Dungeon.");
        add("item.terra_curio.shark_tooth_necklace.info", "It has a chance to drop from Drowned.");
        add("item.terra_curio.shot_put.info", "It can be found in Chests in the Stronghold.");
        add("item.terra_curio.sorcerer_emblem.info", "It have a Chance to be dropped from Evoker.");
        add("item.terra_curio.star_cloak.info", "It can be discovered in chests found within Woodland Mansion.");
        add("item.terra_curio.sun_stone.info", "It have a Chance to be dropped from Blaze.");
        add("item.terra_curio.titan_glove.info", "It can be found in Chests in the Mineshaft.");
        add("item.terra_curio.trifold_map.info", "It can be found in Chests in the Stronghold Library.");
        add("item.terra_curio.vitamins.info", "It have a Chance to be dropped from Witch.");
        add("item.terra_curio.warrior_emblem.info", "It have a Chance to be dropped from Vindicator.");
        add("item.terra_curio.demon_heart.info", "It to be dropped from Wither.");

        add("death.attack.star_cloak", "%1$s was squashed by a falling star");

        add("attribute.name.generic.critical_chance", "Critical Chance");
        add("attribute.name.generic.ranged_velocity", "Ranged Velocity");
        add("attribute.name.generic.ranged_damage", "Ranged Damage");
        add("attribute.name.generic.dodge_chance", "Dodge Chance");
        add("attribute.name.generic.mining_speed", "Mining Speed");
        add("attribute.name.generic.aggro", "Aggro");
        add("attribute.name.generic.magic_damage", "Magic Damage");
        add("attribute.name.generic.armor_pass", "Armor Pass");
        add("attribute.name.generic.pickup_range", "Pickup Range");

        add("container.terra_curio.workshop", "Workshop");
        add("title.terra_curio.workshop", "Workshop");

        add("achievements.terra_curio.boots_of_the_hero.title", "Boots of the Hero");
        add("achievements.terra_curio.boots_of_the_hero.description", "Forged from the finest boots of fire and ice.");
        add("achievements.terra_curio.black_mirror.title", "Black Mirror");
        add("achievements.terra_curio.black_mirror.description", "You'll never leave home without it again.");
        add("achievements.terra_curio.ankhumulation_complete.title", "Ankhumulation Complete");
        add("achievements.terra_curio.ankhumulation_complete.description", "The finest protection from unpleasant maladies and ailments.");

        ModItems.ITEMS.getEntries().forEach(item -> {
            Item item1 = item.get();
            if (item1 instanceof CustomName customName) add(item1, customName.getGenName());
            else add(item1, toTitleCase(item.getId().getPath()));
        });
        ModEntities.ENTITIES.getEntries().forEach(entity -> add(entity.get(), toTitleCase(entity.getId().getPath())));
        ModEffects.EFFECTS.getEntries().forEach(effect -> add(effect.get(), toTitleCase(effect.getId().getPath())));
    }

    private static String toTitleCase(String raw) {
        return Arrays.stream(raw.split("_"))
            .map(word -> Character.toUpperCase(word.charAt(0)) + word.substring(1).toLowerCase())
            .collect(Collectors.joining(" "));
    }
}
